name: Release

on:
  repository_dispatch:
  push:
    branches:
      - release1/*
    tags:
      - "v*"   #Push events to matching v*,i.e. v1.0 v20.15.10
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: image name (python:3.11.10-slim-bookworm)
        required: true

concurrency:
  group: ci-buildtrain-${{ github.ref }}-release-v3
  cancel-in-progress: true

jobs:
  # 启动
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: '["generate_image", "generate_debpackage"]'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: repository
          submodules: true
      - name: Docker version
        shell: bash
        run: |
          # Clean up workspace
          path="${{ github.workspace }}/repository/src/workspace"
            
          docker --version
          docker compose version
      - name: Check docker image
        shell: bash
        run: |
          docker pull ${{ github.event.inputs.version }}
          docker images
